name: Site Monitoring

on:
  schedule:
    # 6時間ごとに実行 (UTC時間)
    - cron: '0 */6 * * *'
  
  # 手動実行も可能
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('monitor/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Cache monitoring state
      uses: actions/cache@v3
      with:
        path: monitor/state/
        key: ${{ runner.os }}-monitor-state-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-monitor-state-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r monitor/requirements.txt
    
    - name: Run site monitoring
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        python -m monitor.main
    
    - name: Upload monitoring logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: monitoring-logs
        path: monitor/state/
        retention-days: 7